SUCCESS = "1000"

CODES = {
    "1000": "Success!",
    "1001": "Unknown Message Received",
    "1002": "Connection to Fishbowl Server was lost",
    "1003": "Some Requests had errors -- now isn't that helpful...",
    "1004": "There was an error with the database.",
    "1009": "Fishbowl Server has been shut down.",
    "1010": "You have been logged off the server by an administrator.",
    "1012": "Unknown request function.",
    "1100": "Unknown login error occurred.",
    "1110": "A new Integrated Application has been added to Fishbowl Inventory. Please contact your Fishbowl Inventory Administrator to approve this Integrated Application.",
    "1111": "This Integrated Application registration key does not match.",
    "1112": "This Integrated Application has not been approved by the Fishbowl Inventory Administrator.",
    "1120": "Invalid Username or Password.",
    "1130": "Invalid Ticket passed to Fishbowl Inventory Server.",
    "1131": "Invalid Key value.",
    "1140": "Initialization token is not correct type.",
    "1150": "Request was invalid",
    "1160": "Response was invalid.",
    "1162": "The login limit has been reached for the server's key.",
    "1200": "Custom Field is invalid.",
    "1500": "The import was not properly formed.",
    "1501": "That import type is not supported",
    "1502": "File not found.",
    "1503": "That export type is not supported.",
    "1504": "File could not be written to.",
    "1505": "The import data was of the wrong type.",
    "2000": "Was not able to find the Part {0}.",
    "2001": "The part was invalid.",
    "2100": "Was not able to find the Product {0}.",
    "2101": "The product was invalid.",
    "2200": "The yield failed.",
    "2201": "Commit failed.",
    "2202": "Add initial inventory failed.",
    "2203": "Can not adjust committed inventory.",
    "2300": "Was not able to find the Tag number {0}.",
    "2301": "The tag is invalid.",
    "2302": "The tag move failed.",
    "2303": "Was not able to save Tag number {0}.",
    "2304": "Not enough available inventory in Tagnumber {0}.",
    "2305": "Tag number {0} is a location.",
    "2400": "Invalid UOM.",
    "2401": "UOM {0} not found.",
    "2402": "Integer UOM {0} cannot have non-integer quantity.",
    "2500": "The Tracking is not valid.",
    "2510": "Serial number is missing.",
    "2511": "Serial number is null.",
    "2512": "Serial number is duplicate.",
    "2513": "Serial number is not valid.",
    "2600": "Location not found.",
    "2601": "Invalid location.",
    "2602": "Location Group {0} not found.",
    "3000": "Customer {0} not found.",
    "3001": "Customer is invalid.",
    "3100": "Vendor {0} not found.",
    "3101": "Vendor is invalid.",
    "4000": "There was an error load PO {0}.",
    "4001": "Unknow status {0}.",
    "4002": "Unknown carrier {0}.",
    "4003": "Unknown QuickBooks class {0}.",
    "4004": "PO does not have a PO number. Please turn on the auto-assign PO number option in the purchase order module options.",
}


def get_status(code):
    return CODES.get(str(code), "Unknown status")
